from typing import Dict, Any

ALGORITHM_METADATA: Dict[str, Dict[str, Any]] = {
    "DES": {
        "type": "Symmetric Encryption",
        "default_mode": "Unknown / Not Determined",
        "default_key_size": "56-bit",
        "severity": "CRITICAL",
        "reason": "DES has an obsolete 56-bit key length and is vulnerable to practical brute-force cracking within hours.",
        "recommendation": "Migrate to AES-256 in an authenticated mode such as GCM (AES-GCM) or ChaCha20-Poly1305.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "HIGH",
        "exposure_reason": "Broken symmetric cipher with inadequate 56-bit keyspace allows trivial plaintext recovery.",
        "migration_effort": "LOW",
        "migration_time_estimate": "1–2 weeks",
        "migration_reason": "Symmetric algorithm replacement requiring cipher parameter update and data re-encryption."
    },
    "3DES": {
        "type": "Symmetric Encryption",
        "default_mode": "Unknown / Not Determined",
        "default_key_size": "112/168-bit",
        "severity": "HIGH",
        "reason": "Triple-DES (3DES / DESede) has small 64-bit block size making it vulnerable to Sweet32 collision attacks. Deprecated by NIST.",
        "recommendation": "Replace 3DES with AES-256-GCM or AES-128-GCM.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "HIGH",
        "exposure_reason": "Sweet32 collision vulnerabilities on 64-bit blocks risk ciphertext decryption on high-traffic connections.",
        "migration_effort": "LOW",
        "migration_time_estimate": "1–2 weeks",
        "migration_reason": "Direct cipher substitution to AES-GCM; key storage and message format update."
    },
    "RC4": {
        "type": "Symmetric Encryption (Stream Cipher)",
        "default_mode": "Stream",
        "default_key_size": "Variable (40–2048 bit)",
        "severity": "CRITICAL",
        "reason": "RC4 exhibits statistical biases in initial keystream bytes (Bar Mitzvah, RC4 NOMORE) allowing plaintext recovery.",
        "recommendation": "Cease all RC4 usage immediately; migrate to AES-GCM or ChaCha20-Poly1305.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "HIGH",
        "exposure_reason": "Keystream biases allow passive network observers to reconstruct credentials and session tokens.",
        "migration_effort": "LOW",
        "migration_time_estimate": "1–2 weeks",
        "migration_reason": "Replace stream cipher with authenticated modern symmetric cipher scheme."
    },
    "AES-128": {
        "type": "Symmetric Encryption",
        "default_mode": "Unknown / Not Determined",
        "default_key_size": "128-bit",
        "severity": "LOW",
        "reason": "AES-128 remains classically secure, but Grover's quantum algorithm halves effective symmetric security to 64 bits.",
        "recommendation": "For long-term confidential data protection against future quantum attacks, consider transitioning to AES-256.",
        "quantum_risk": "MEDIUM",
        "pqc_migration_candidate": "Not Immediate",
        "exposure_level": "LOW",
        "exposure_reason": "No immediate classical compromise known; long-term data may face reduced quantum security margin.",
        "migration_effort": "LOW",
        "migration_time_estimate": "1–2 weeks",
        "migration_reason": "Key length upgrade from 128-bit to 256-bit with existing AES libraries."
    },
    "AES-256": {
        "type": "Symmetric Encryption",
        "default_mode": "Unknown / Not Determined",
        "default_key_size": "256-bit",
        "severity": "LOW",
        "reason": "Modern NIST-standard symmetric cipher. Highly resilient to both classical attacks and Grover's quantum algorithm.",
        "recommendation": "Ensure authenticated operation mode (e.g. GCM) is utilized and unique nonces/IVs are strictly enforced.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "LOW",
        "exposure_reason": "Strong 256-bit key and modern block structure provide robust confidentiality and integrity.",
        "migration_effort": "NOT REQUIRED",
        "migration_time_estimate": "Not Required",
        "migration_reason": "AES-256 provides 128 bits of post-quantum security against Grover's algorithm; no PQC migration is immediately required."
    },
    "AES": {
        "type": "Symmetric Encryption",
        "default_mode": "Unknown / Not Determined",
        "default_key_size": "128/256-bit",
        "severity": "LOW",
        "reason": "NIST standard Advanced Encryption Standard. Secure when used with authenticated modes (GCM, CCM, OCB).",
        "recommendation": "Ensure authenticated encryption modes (such as GCM) are used instead of legacy unauthenticated modes like ECB.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "LOW",
        "exposure_reason": "Standard modern cipher; exposure is low provided unauthenticated modes (ECB) are not used.",
        "migration_effort": "NOT REQUIRED",
        "migration_time_estimate": "Not Required",
        "migration_reason": "Modern symmetric encryption remains resilient; verify mode configuration."
    },
    "MD5": {
        "type": "Hash Function",
        "default_mode": "Digest",
        "default_key_size": "128-bit digest",
        "severity": "HIGH",
        "reason": "MD5 suffers from severe collision vulnerabilities (Flame malware, chosen-prefix collisions) and fast rainbow table reversals.",
        "recommendation": "Migrate to SHA-256, SHA-3, or password-hashing schemes (Argon2id, bcrypt) for authentication.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "MEDIUM",
        "exposure_reason": "Hash collision attacks allow signature forgery; fast cracking exposes hashed secrets.",
        "migration_effort": "LOW",
        "migration_time_estimate": "1–2 weeks",
        "migration_reason": "Replace hashing digest calls with SHA-256 or Argon2id."
    },
    "SHA-1": {
        "type": "Hash Function",
        "default_mode": "Digest",
        "default_key_size": "160-bit digest",
        "severity": "HIGH",
        "reason": "Practical collision attacks (SHAttered, SHA-1 is a Shambles) have broken SHA-1 collision resistance. Deprecated globally.",
        "recommendation": "Upgrade to SHA-256 or SHA-512 from the SHA-2 family, or SHA-3.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "MEDIUM",
        "exposure_reason": "Risk of collision-based digital signature falsification and message tampering.",
        "migration_effort": "LOW",
        "migration_time_estimate": "1–2 weeks",
        "migration_reason": "Update hashing routines and certificate/signature verification logic to SHA-256."
    },
    "SHA-256": {
        "type": "Hash Function",
        "default_mode": "Digest",
        "default_key_size": "256-bit digest",
        "severity": "LOW",
        "reason": "Robust cryptographic hash function widely accepted across industry and government standards.",
        "recommendation": "Maintain usage; consider HMAC-SHA256 for message authentication or HKDF for key derivation.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "LOW",
        "exposure_reason": "Strong preimage and collision resistance protect data integrity.",
        "migration_effort": "NOT REQUIRED",
        "migration_time_estimate": "Not Required",
        "migration_reason": "Standard 256-bit hashing provides adequate pre- and post-quantum collision margins."
    },
    "SHA-384": {
        "type": "Hash Function",
        "default_mode": "Digest",
        "default_key_size": "384-bit digest",
        "severity": "LOW",
        "reason": "High-security cryptographic hash function from the SHA-2 family.",
        "recommendation": "Maintained as secure by standard cryptographic guidelines.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "LOW",
        "exposure_reason": "Strong cryptographic digest properties.",
        "migration_effort": "NOT REQUIRED",
        "migration_time_estimate": "Not Required",
        "migration_reason": "Adequate post-quantum security margin under Grover's algorithm."
    },
    "SHA-512": {
        "type": "Hash Function",
        "default_mode": "Digest",
        "default_key_size": "512-bit digest",
        "severity": "LOW",
        "reason": "High-security member of SHA-2 family, optimal for 64-bit CPU architectures.",
        "recommendation": "Maintain usage; acceptable for high-security applications.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "LOW",
        "exposure_reason": "Superior security margin against classical and quantum collision search.",
        "migration_effort": "NOT REQUIRED",
        "migration_time_estimate": "Not Required",
        "migration_reason": "No PQC migration needed for SHA-512 digests."
    },
    "SHA-3": {
        "type": "Hash Function",
        "default_mode": "Digest",
        "default_key_size": "Variable (224–512 bit)",
        "severity": "LOW",
        "reason": "NIST Keccak sponge-construction standard providing diverse structural defense against SHA-2 vulnerabilities.",
        "recommendation": "Ideal for next-generation systems and cryptographic agility.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "LOW",
        "exposure_reason": "State-of-the-art cryptographic sponge permutation.",
        "migration_effort": "NOT REQUIRED",
        "migration_time_estimate": "Not Required",
        "migration_reason": "No PQC migration needed."
    },
    "RSA-1024": {
        "type": "Asymmetric Cryptography",
        "default_mode": "Public-Key Encryption / Signature",
        "default_key_size": "1024-bit",
        "severity": "HIGH",
        "reason": "1024-bit RSA provides approximately 80 bits of security, vulnerable to distributed factorization by nation-state actors. Shor's quantum algorithm breaks it completely.",
        "recommendation": "Immediately upgrade to at least RSA-3072 or ECC (NIST P-384) for classical security, and plan post-quantum transition (e.g., ML-KEM / ML-DSA).",
        "quantum_risk": "HIGH",
        "pqc_migration_candidate": "Candidate",
        "exposure_level": "VERY HIGH",
        "exposure_reason": "Weak key size allows classical integer factorization; long-term encrypted data subject to 'Harvest Now, Decrypt Later' (HNDL) quantum threats.",
        "migration_effort": "MEDIUM",
        "migration_time_estimate": "2–6 weeks",
        "migration_reason": "Requires key regeneration, certificate reissuance, API client trust updates, and PQC transition planning."
    },
    "RSA": {
        "type": "Asymmetric Cryptography",
        "default_mode": "Public-Key Encryption / Signature",
        "default_key_size": "Unknown / Not Determined",
        "severity": "MEDIUM",
        "reason": "RSA relies on the integer factorization problem, which is completely breakable by Shor's quantum algorithm on Cryptographically Relevant Quantum Computers (CRQCs).",
        "recommendation": "Adopt cryptographic agility and prepare migration toward NIST PQC standards (ML-KEM/FIPS 203 for KEM, ML-DSA/FIPS 204 for signatures).",
        "quantum_risk": "HIGH",
        "pqc_migration_candidate": "Candidate",
        "exposure_level": "MEDIUM",
        "exposure_reason": "Public-key exchange and signatures are vulnerable to store-now-decrypt-later quantum attacks.",
        "migration_effort": "MEDIUM",
        "migration_time_estimate": "2–6 weeks",
        "migration_reason": "Migration requires protocol negotiation, hybrid PQC/classical KEM schemes, and library updates."
    },
    "ECC": {
        "type": "Asymmetric Cryptography",
        "default_mode": "Key Agreement / Signature",
        "default_key_size": "256/384-bit",
        "severity": "LOW",
        "reason": "Classically strong, but Elliptic Curve Discrete Logarithm Problem is completely solvable in polynomial time by Shor's quantum algorithm.",
        "recommendation": "Prepare hybrid key exchange (e.g. X25519 + ML-KEM-768) to protect against Harvest Now Decrypt Later adversary strategies.",
        "quantum_risk": "HIGH",
        "pqc_migration_candidate": "Candidate",
        "exposure_level": "LOW",
        "exposure_reason": "Classically robust; high quantum risk for long-lived confidential sessions.",
        "migration_effort": "MEDIUM",
        "migration_time_estimate": "2–6 weeks",
        "migration_reason": "Integration of post-quantum KEM / signature algorithms in key establishment protocols."
    },
    "ECDSA": {
        "type": "Digital Signature",
        "default_mode": "Signature",
        "default_key_size": "256/384-bit",
        "severity": "LOW",
        "reason": "Classically secure digital signature scheme; vulnerable to quantum forgery via Shor's algorithm.",
        "recommendation": "Plan migration to stateful hash-based signatures (LMS, XMSS) or lattice-based signatures (ML-DSA / FIPS 204, SLH-DSA / FIPS 205).",
        "quantum_risk": "HIGH",
        "pqc_migration_candidate": "Candidate",
        "exposure_level": "LOW",
        "exposure_reason": "Classically intact; post-quantum threat to digital non-repudiation and code signing.",
        "migration_effort": "MEDIUM",
        "migration_time_estimate": "2–6 weeks",
        "migration_reason": "Public key infrastructure and verification pipeline migration to ML-DSA."
    },
    "Ed25519": {
        "type": "Digital Signature",
        "default_mode": "Signature",
        "default_key_size": "256-bit",
        "severity": "LOW",
        "reason": "Modern Edwards-curve signature scheme. Strong classical resilience; susceptible to quantum discrete log attacks.",
        "recommendation": "Prepare hybrid signatures or migration to NIST PQC digital signature standards (FIPS 204 ML-DSA).",
        "quantum_risk": "HIGH",
        "pqc_migration_candidate": "Candidate",
        "exposure_level": "LOW",
        "exposure_reason": "Secure against classical attacks; vulnerable to future CRQC signature forgery.",
        "migration_effort": "MEDIUM",
        "migration_time_estimate": "2–6 weeks",
        "migration_reason": "Signature verification engine refactoring to support post-quantum signature schemes."
    },
    "HMAC": {
        "type": "Message Authentication Code (MAC)",
        "default_mode": "Authentication Tag",
        "default_key_size": "Variable",
        "severity": "LOW",
        "reason": "Keyed-hash message authentication code. Security depends directly on underlying hash function and key secrecy.",
        "recommendation": "Ensure HMAC is paired with SHA-256 or better (HMAC-SHA256). Avoid HMAC-MD5 or HMAC-SHA1.",
        "quantum_risk": "LOW",
        "pqc_migration_candidate": "Not Required",
        "exposure_level": "LOW",
        "exposure_reason": "Symmetric authentication tags are resilient against quantum forgery when using adequate key sizes.",
        "migration_effort": "NOT REQUIRED",
        "migration_time_estimate": "Not Required",
        "migration_reason": "Symmetric MAC functions remain quantum-safe; ensure underlying hash is SHA-256 or higher."
    },
    "TLS": {
        "type": "Transport Layer Security",
        "default_mode": "Transport Protocol",
        "default_key_size": "Protocol Config",
        "severity": "INFORMATIONAL",
        "reason": "TLS configuration detected. Security posture depends on protocol version (TLS 1.3 is recommended).",
        "recommendation": "Enforce TLS 1.3, disable TLS 1.0/1.1 and legacy cipher suites (CBC, RC4, 3DES).",
        "quantum_risk": "MEDIUM",
        "pqc_migration_candidate": "Candidate",
        "exposure_level": "LOW",
        "exposure_reason": "Transport security depends on negotiated cipher suites and key exchange algorithms.",
        "migration_effort": "MEDIUM",
        "migration_time_estimate": "2–6 weeks",
        "migration_reason": "Enable hybrid post-quantum key exchange (X25519Kyber768 / X25519MLKEM768) in web servers and TLS clients."
    }
}
